{% set version = "0.9.9" %}

package:
  name: hyperion-fortran
  version: {{version}}

source:
  fn: Hyperion-{{version}}.tar.gz
  url: https://pypi.io/packages/source/h/hyperion/Hyperion-{{version}}.tar.gz
  md5: e1db1082e46bf69db0cc5f392b454eba

build:
  number: 0
  skip: True  # [win]

requirements:

  build:
    - hdf5 1.8.18|1.8.18.*
    - mpich
    - gcc  # [not win]

  run:
    - hdf5 1.8.18|1.8.18.*
    - mpich
    - libgfortran  # [not win]

test:
  files:
    - amr.rtin
    - car.rtin
    - cyl.rtin
    - oct.rtin
    - sph.rtin
    - vor.rtin

about:
  home: https://github.com/hyperion-rt/hyperion
  license: BSD 2-Clause
  summary: Hyperion Radiation Transfer Code

extra:
  recipe-maintainers:
    - astrofrog
