# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: generic

os: osx

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "2be4G/FrIF5XPIDTcSA+N3iG+AUzYzjBxsbYcu6670QqeSn7FBEIyxIvR4Y0TGfXfCUTTajrN2zeUpPW1pgqwsny3MPn0bcivYRj+z+8fjk1YLPh7RODSNGhPG+1VBlTxPR9PhjscLF8LUeaERM6LaXIMyXdg4aW3KiyLzAE0ubIwdToiTGC5T9xqdftbwACdipvNZY87T7M5X1ir3MwTZ60Yg7wYEdPOxsT8QtlrDDuE/Rb/cWJqaWVnTF2lpizItsXLCVPGN8ToWlYqQTDVc0RRRXt624GzVjDfZ3cExhdlmRua9eOc1A1KtOX77Qm1rE7T00VbkzEtatPr/FwdfbRPrlgaqbEUGKVtmj7Zr3hkW4cZ7O3iOihECCUySpvOuznBJzoIPzZdzuFJE1EbnxGyrNe3Iog+NSHO2gAKzfN8R/abnFsudhUgl2MikAtv/sG6wyfAvfBZ1VObDzevZ60OWhofQ4cdKhv7uQIrd61AOcC5y52git8NuHfWJwEMhZx0XobDAx2aAA95edgqbfZD6Xw9xMSb3CI8K/yYpZPb0cr7sq2kpr+2aEbiWwAzwqIzagOKBJGFcwl2wIbNuEkmIEK3GDyihXRVq1i1zNUSIUYaWqq/gxbKM12d0jjBkq9p7ja3NspTRovlTPjJWjY3LQ1Wcm55ZVnKzlGV7g="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
