travis:
  secure:
    BINSTAR_TOKEN: 2be4G/FrIF5XPIDTcSA+N3iG+AUzYzjBxsbYcu6670QqeSn7FBEIyxIvR4Y0TGfXfCUTTajrN2zeUpPW1pgqwsny3MPn0bcivYRj+z+8fjk1YLPh7RODSNGhPG+1VBlTxPR9PhjscLF8LUeaERM6LaXIMyXdg4aW3KiyLzAE0ubIwdToiTGC5T9xqdftbwACdipvNZY87T7M5X1ir3MwTZ60Yg7wYEdPOxsT8QtlrDDuE/Rb/cWJqaWVnTF2lpizItsXLCVPGN8ToWlYqQTDVc0RRRXt624GzVjDfZ3cExhdlmRua9eOc1A1KtOX77Qm1rE7T00VbkzEtatPr/FwdfbRPrlgaqbEUGKVtmj7Zr3hkW4cZ7O3iOihECCUySpvOuznBJzoIPzZdzuFJE1EbnxGyrNe3Iog+NSHO2gAKzfN8R/abnFsudhUgl2MikAtv/sG6wyfAvfBZ1VObDzevZ60OWhofQ4cdKhv7uQIrd61AOcC5y52git8NuHfWJwEMhZx0XobDAx2aAA95edgqbfZD6Xw9xMSb3CI8K/yYpZPb0cr7sq2kpr+2aEbiWwAzwqIzagOKBJGFcwl2wIbNuEkmIEK3GDyihXRVq1i1zNUSIUYaWqq/gxbKM12d0jjBkq9p7ja3NspTRovlTPjJWjY3LQ1Wcm55ZVnKzlGV7g=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
