travis:
  secure:
    BINSTAR_TOKEN: EE81CkAnIGoLadekS27dG0TWU8U3ZM6P0A3VeosAIwrpCEqCkPnv6MTY7GOfuMy0O6Ia7HNpOglPvJayyl0CN7URAA04705okRkOal3oDjrJuEOv3Mk0VDqNVLF7li8QEgwzR6Lpf9LwEUHqIrdDkQOovEjUmxoe5wez96Sye6k4T5xz3Q32PlPvY+8CiQtoJywRnVgisuzDni+4iTPjLGTIg+9os2cLEglX2kqC3hklEPmJQXCTzkrDwvxgx3zGJcNomUr4M9QV3U2rBFhSRaveRsTBFXSxTAJ+VOMKEOLOIEjdz0U57VkorASmIQ8CU7ChfygafrgWYJIwQVYWLtVXRvJg7ttwqT/RxiiG4mX+VYNilOR1jGtRe0o3KRQ6dQ4SR+4P1VsRgwD149lFGjMmrc0w2HHnxnzCCuNmQwMZ1RwLoyF2c46H4E2C9Z7oO6uqI4ol5tzM8hk+rdjGFLxIJanP/TPkOG/b4mmVBkqA0AUflYeWw+9Sh5gexM5Tow23uR7L/Q7t9lL0F0qDFgbtuzU+2s9lUUA6IfEvrR+gdAnKHZuc3Z9r40QKC6WfO/RmZbbKANeOM2QuhkpaYsdk0mBFPsPkEz0ORXDTZMTQSknbO3EMJEysGFcc/83tfBJPQWovtOlBi8qYsrHHm4g9QsOVkTHclOBYg8rTVeI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
